In [1]:
import cv2

In [2]:
import numpy as np, sys 

In [3]:
A = cv2.imread('img.jpg')
B = cv2.imread('img.jpg')

In [8]:
#生成高斯图像金字塔
G = A.copy()
gpA = [G]
for i in range(6):
    G = cv2.pyrDown(G)
    print(G)
    gpA.append(G)
print(gpA)

G = B.copy()
gpB = [G]
for i in range(6):
    G = cv2.pyrDown(G)
    gpB.append(G)
print(gpB)

[[[247 225 139]
  [249 228 142]
  [249 228 143]
  ...
  [234 194 108]
  [230 190 101]
  [231 193  99]]

 [[246 223 137]
  [250 228 142]
  [250 230 144]
  ...
  [235 197 110]
  [231 193 103]
  [233 195 102]]

 [[245 222 134]
  [248 225 138]
  [250 229 143]
  ...
  [230 194 105]
  [230 196 104]
  [230 196 102]]

 ...

 [[251 254 182]
  [250 253 181]
  [250 253 181]
  ...
  [253 236 149]
  [250 233 146]
  [248 231 144]]

 [[251 254 182]
  [251 254 182]
  [250 253 181]
  ...
  [253 236 149]
  [252 235 148]
  [251 234 147]]

 [[252 255 183]
  [252 255 183]
  [252 255 183]
  ...
  [254 237 150]
  [255 238 151]
  [255 238 151]]]
[[[248 226 140]
  [248 227 142]
  [246 227 145]
  ...
  [232 197 105]
  [233 195 108]
  [232 194 104]]

 [[248 225 138]
  [249 227 141]
  [248 228 144]
  ...
  [231 198 102]
  [230 195 106]
  [230 195 104]]

 [[249 224 134]
  [251 227 138]
  [251 230 143]
  ...
  [230 196 101]
  [228 195 109]
  [231 201 116]]

 ...

 [[249 252 180]
  [247 251 179]
  [249 252 180]
  ..

In [27]:
#对A产生laplacian
lpA = [gpA[5]]
print(type(lpA))
for i in range(5,0,-1):
    GE = cv2.pyrUp(gpA[i])
    #print(type(GE))
    #print('------------------------')
    #print(type(gpA))
    L = cv2.subtract(np.asarray(gpA[i-1]),GE)
    lpA.append(L)

<class 'list'>


error: OpenCV(3.4.2) C:\Miniconda3\conda-bld\opencv-suite_1534379934306\work\modules\core\src\arithm.cpp:659: error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array' in function 'cv::arithm_op'
